# Generated by Django 5.1 on 2024-09-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_financialrecord_harvest_irrigationsystem_medicine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
